### ISSUE TITLE
CSS race condition

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-css#20]
I'm not sure why, but I'm seeing this error occasionally when trying to run `canjs/canjs`:

![_canjs_tests_and_downloads](https://cloud.githubusercontent.com/assets/78602/19500975/717300b8-9567-11e6-9300-cca377cc0000.png)

System appears to be traceur's system:

![canjs_tests](https://cloud.githubusercontent.com/assets/78602/19501007/af4a2268-9567-11e6-9691-a916ea6b873f.png)

This is likely because `steal-css` should be using `loader` instead of `System` here: https://github.com/stealjs/steal-css/blob/v0.4.1/css.js#L69

**Comment by justinbmeyer** [comment]
switching to `loader` fixes the issue

**Comment by matthewp** [comment]
This was caused by https://github.com/stealjs/steal/issues/867 and since fixed.
