### ISSUE TITLE
typo throws error; breaks live reloading

### ISSUE THREAD

**Issue by Bajix** [stealjs/steal-css#26]
`load.name` should be `name`.

https://github.com/stealjs/steal-css/blob/master/css.js#L190

**Comment by Bajix** [comment]
@matthewp 1.1.0 should be unpublished; I believe this needs to happen within the next 12 hours.

**Comment by matthewp** [comment]
Please don't ask for timelines for things that you aren't paying for.

**Comment by Bajix** [comment]
It's a timeline set by npm, not me; you can't unpublish version after 24 hours has passed.

**Comment by matthewp** [comment]
Ah ok, sorry for the mix up then.

**Comment by matthewp** [comment]
I published your fix as 1.1.1 anyways, no need to unpublish.

**Comment by Bajix** [comment]
kk
