### ISSUE TITLE
CSS is parsed as JSON if file starts with an attribute selector

### ISSUE THREAD

**Issue by phillipskevin** [stealjs/steal-css#32]
Reported [on gitter](https://gitter.im/stealjs/steal?at=58c01584e961e53c7fb7f44e). If a CSS file starts with an attribute selector (like `[name="test"]`), steal-css will try to parse it as JSON:

![image](https://cloud.githubusercontent.com/assets/5851984/23756510/8024b0dc-04a9-11e7-8076-f7ecfbcef09b.png)

**Comment by matthewp** [comment]
Most likely a bug in Steal itself, the json extension would be my guess.

**Comment by phillipskevin** [comment]
Issue moved to [stealjs/steal #1092](https://github.com/stealjs/steal/issues/1092) via [**ZenHub**](https://www.zenhub.com/)
