### ISSUE TITLE
In optimized build, links are injected multiple times

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-css#64]
Because the optimizer doesn't resolve to URLs, the check to see if a `<link>` already exists in the page will always be falsey. The fix is to use either `URL()` or `<a>` to get the href relative to the page, and use that as the check.

**Comment by m-mujica** [comment]
I'm seeing this in bitballs 

![screen shot 2018-01-24 at 10 07 12 am](https://user-images.githubusercontent.com/724877/35346052-6a9ab594-00ee-11e8-82b5-0728f1a8ea35.png)

doing some debugging, it happens b/c `document.styleSheets` comes out empty each time the css slim plugin is called (even tho there are links already on the header, not sure why)

![screen shot 2018-01-24 at 10 08 55 am](https://user-images.githubusercontent.com/724877/35346127-9f100ca2-00ee-11e8-903b-e207399aeede.png)
